---
- name: Check server time
  hosts: all
  gather_facts: false

  tasks:
    - name: Get_uptime server
      command: uptime
      register: server_uptime

    - name: Show current time
      debug:
        msg: "{{ server_uptime.stdout }}"

